### ISSUE TITLE
How do you write your content in tamil?

### ISSUE THREAD

**Issue by kishvanchee** [tamil-blog/tamil-blog.github.io#6]
Hi, pardon my ignorance. How do you write your content in markdown in tamil? Can you please also link how tamil gets supported through jekyll/githubpages?

**Comment by smileprem** [comment]
Hi Kishore - I use google transliteration tool for writing in Tamil. The text you copy from the google transliteration website is UTF encoded. It is supported by default (like English)

https://www.google.com/inputtools/try/

Thanks,
Prem
